// Code generated by MockGen. DO NOT EDIT.
// Source: asymptotic.world/api/phonebook/v1 (interfaces: Database)
//
// Generated by this command:
//
//	mockgen -destination=mock_database_test.go -package=v1 . Database
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// GetPerson mocks base method.
func (m *MockDatabase) GetPerson(ctx context.Context, name string) (*Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", ctx, name)
	ret0, _ := ret[0].(*Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson.
func (mr *MockDatabaseMockRecorder) GetPerson(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockDatabase)(nil).GetPerson), ctx, name)
}

// SavePerson mocks base method.
func (m *MockDatabase) SavePerson(ctx context.Context, p *Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePerson", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePerson indicates an expected call of SavePerson.
func (mr *MockDatabaseMockRecorder) SavePerson(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePerson", reflect.TypeOf((*MockDatabase)(nil).SavePerson), ctx, p)
}
